apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
spec:
  cidrs:
    - "192.168.1.60/32"
    - "192.168.1.61/32"
  serviceSelector:
    matchLabels:
      "io.cilium/lb-ip-pool": "homelab-pool"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-policy
spec:
  nodeSelector:
    matchExpressions:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "DoesNotExist"
  interfaces:
    - eth0
  externalIPs: true
  loadBalancerIPs: true